kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  namespace: develop
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
